# Generated by Django 4.1.1 on 2022-09-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('device_name', models.CharField(max_length=255)),
                ('device_model', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
