# Generated by Django 4.1.1 on 2022-09-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbwphone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecatalog',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
